### ISSUE TITLE
calculating distance of schools to providers

### ISSUE THREAD

**Issue by jrosen48** [OR-K-Entry/ec-providers#2]
is this a worthy task to pursue?

if so, would you recommend using {sf}, perhaps the `st_distance()` function? Would this require creating {sf} objects for both the nces/school and the providers data? I'm imagining something like the below as a way to think about how to do this for one school, after which we could apply it to all), but wanted to touch base before going *any* further than this:

```
one_school <- nces[1, ]

find_distance_of_providers_for_one_school <- function(school_data, providers_data) {
  
### PSEUDOCODE
school_sf <- create_sf_object(school_data)
providers_sf <- create_sf_object(providers_data)

distance_of_every_provider_to_school <- map(providers_sf) %>%
    st_distance(school_sf)

# something else
}

find_distance_of_providers_for_one_school(one_school, providers)
```

**Comment by datalorax** [comment]
Is `st_distance` different than as-the-crow-flies distance? Probably a bit more accurate because it  probs takes into account the curvature of the earth, but I wonder if this is sufficiently different from just calculating Mahalanobis distance. 

I liked your idea though of maybe hitting a google API or something for street directions. That might give the most accurate estimate.

Here's a link to the google maps API for directions. Looks like it could give time to between destinations but I'm not sure if it works with lat/lon as the inputs. Probably does, but I'm just not sure. https://developers.google.com/maps/documentation/directions/start?hl=en_US

**Comment by datalorax** [comment]
Also, though, this seems like something we could refine later. For now, I would suggest we just calculate Mahalanobis distance and begin to try to fit the model as just sort of a proof of concept for the modeling framework. Thoughts?

**Comment by jrosen48** [comment]
I think I forgot how... space... 🤣works. Can you calculate the Mahalanobis distance without using {sf} - just from the lat and lon, right?

**Comment by jrosen48** [comment]
I was (incorrectly) thinking that we needed to use {sf} to calculate even the Mah distance.

**Comment by datalorax** [comment]
I'm pretty sure that's right, but I just did some sleuthing and maybe it's not quite as easy as I thought... I unfortunately can't devote time to this today but will try to circle back early next week.

**Comment by jrosen48** [comment]
sounds good

**Comment by jrosen48** [comment]
I can close this for now, and plan to circle back to this if/when we use the Google Maps API.
